### ISSUE TITLE
local_tags_cache does not always exist

### ISSUE THREAD

**Issue by mserajnik** [mserajnik/hyve#10]
A user encountered the following error when syncing to hydrus client:

```
hyve-sync_1    | Error while trying to sync.
hyve-sync_1    |  SqliteError: no such table: hydrus_caches_db.local_tags_cache
hyve-sync_1    |     at fillNewTagsTable (/usr/src/app/services/sync-client/src/sync/index.js:244:11)
hyve-sync_1    |     at Object.run (/usr/src/app/services/sync-client/src/sync/index.js:37:3)
hyve-sync_1    |     at Object.<anonymous> (/usr/src/app/services/sync-client/bin/sync:94:10)
hyve-sync_1    |     at Module._compile (internal/modules/cjs/loader.js:1123:30)
hyve-sync_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
hyve-sync_1    |     at Module.load (internal/modules/cjs/loader.js:972:32)
hyve-sync_1    |     at Function.Module._load (internal/modules/cjs/loader.js:872:14)
hyve-sync_1    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
hyve-sync_1    |     at internal/main/run_main_module.js:17:47
hyve-sync_1    | time="2020-04-24T10:29:55Z" level=info msg="read crontab: .crontab"
```

I previously assumed that this table should always exist, but that is apparently not the case; maybe swapping the table for a different one that's guaranteed to exist might be sanest option.

**Edit:** After some initial investigation, the table not existing might be a bug in hydrus with specific upgrade scenarios.

**Comment by mserajnik** [comment]
This seems to be a bug in hydrus, according to its developer, the table should always exist. No changes needed in hyve.
